//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgumentyIFakty.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticlesWithWordMigra
    {
        public string Title { get; set; }
        public System.DateTime DatePublished { get; set; }
        public string Author { get; set; }
        public string Context { get; set; }
        public string Url { get; set; }
        public string EditionName { get; set; }
    }
}
